/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar cartas
         * @description Devuelve una página del catálogo propio. La implementación consulta primero la caché y responde con los elementos de la página y el total disponible.
         */
        get: operations["listCards"];
        put?: never;
        /**
         * Crear una carta
         * @description Incorpora al catálogo propio una carta ya transformada desde la fuente externa y actualiza la caché.
         */
        post: operations["createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar una carta
         * @description Devuelve una carta persistida del catálogo propio.
         */
        get: operations["getCard"];
        put?: never;
        post?: never;
        /**
         * Eliminar una carta
         * @description Elimina la carta del catálogo propio y de la caché.
         */
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        /**
         * Actualizar una carta
         * @description Actualiza los campos enviados de una carta persistida y refresca su caché.
         */
        patch: operations["updateCard"];
        trace?: never;
    };
    "/card-listings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar publicaciones de cartas
         * @description Consulta caché y PostgreSQL. En un cold miss canónico crea o reutiliza un trabajo durable y responde 202. Los datos vencidos se sirven mientras se refrescan en segundo plano.
         */
        get: operations["searchCardListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-listings/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar el estado de un trabajo de scraping */
        get: operations["getCardListingScrapeJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-listings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar publicaciones guardadas */
        get: operations["listCardListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-listings/{card_listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar una publicación de carta */
        get: operations["getCardListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Welcome */
        get: operations["welcome__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardCreate */
        CardCreate: {
            /**
             * Ygoid
             * @description Identificador de la carta en la fuente externa de Yu-Gi-Oh!.
             */
            ygoId: number;
            /**
             * Sets
             * @description Sets recibidos de la fuente externa, todavía sin normalizar en campos propios.
             */
            sets: {
                [key: string]: unknown;
            };
            /**
             * Cardtype
             * @description Tipo de carta (Mágica, Trampa, Monstruo)
             */
            cardType: string;
            /**
             * Race
             * @description Tipo de monstruo.
             */
            race: string;
            /**
             * Name
             * @description Nombre oficial de la carta.
             */
            name: string;
            /**
             * Text
             * @description Texto oficial de la carta.
             */
            text: string;
            /**
             * Attribute
             * @description Atributo de la carta.
             */
            attribute: string;
            /**
             * Prices
             * @description Precios externos de referencia; no representan el precio definitivo de una Orden.
             */
            prices: {
                [key: string]: unknown;
            };
            /**
             * Images
             * @description Metadatos externos de imágenes, todavía sin normalizar.
             */
            images: {
                [key: string]: unknown;
            };
        };
        /** CardListResponse */
        CardListResponse: {
            /** Items */
            items: components["schemas"]["CardResponse"][];
            /** Total */
            total: number;
        };
        /** CardListingListResponse */
        CardListingListResponse: {
            /** Items */
            items: components["schemas"]["CardListingResponse"][];
            /** Total */
            total: number;
        };
        /** CardListingResponse */
        CardListingResponse: {
            /**
             * Id
             * @description Identificador interno; nulo si el resultado aún no fue persistido.
             */
            id?: number | null;
            /**
             * Cardid
             * @description Carta interna vinculada; nula mientras no exista la asociación.
             */
            cardId?: number | null;
            /**
             * Ygoid
             * @description Identificador externo de la carta, si pudo resolverse.
             */
            ygoId?: number | null;
            /**
             * Ygoset
             * @description Set anunciado por la publicación externa.
             */
            ygoSet: string;
            /**
             * Name
             * @description Nombre de la carta en la publicación.
             */
            name: string;
            /**
             * Code
             * @description Código de set de la publicación.
             */
            code: string;
            /**
             * Price
             * @description Precio unitario observado en la fuente externa, en USD.
             */
            price: string;
            /**
             * Rarity
             * @description Rareza anunciada.
             */
            rarity: string;
            /**
             * Condition
             * @description Condición anunciada.
             */
            condition: string;
            /**
             * Stock
             * @description Cantidad disponible observada; cero indica falta de stock.
             * @default 0
             */
            stock: number;
            /**
             * Source
             * @default coolstuffinc
             */
            source: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Lastseenat */
            lastSeenAt?: string | null;
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /**
             * Dateadded
             * @description Fecha de persistencia; nula para resultados aún no guardados.
             */
            dateAdded?: string | null;
            /**
             * Dateupdated
             * @description Última actualización persistida, si ocurrió.
             */
            dateUpdated?: string | null;
        };
        /** CardResponse */
        CardResponse: {
            /**
             * Ygoid
             * @description Identificador de la carta en la fuente externa de Yu-Gi-Oh!.
             */
            ygoId: number;
            /**
             * Sets
             * @description Sets recibidos de la fuente externa, todavía sin normalizar en campos propios.
             */
            sets: {
                [key: string]: unknown;
            };
            /**
             * Cardtype
             * @description Tipo de carta (Mágica, Trampa, Monstruo)
             */
            cardType: string;
            /**
             * Race
             * @description Tipo de monstruo.
             */
            race: string;
            /**
             * Name
             * @description Nombre oficial de la carta.
             */
            name: string;
            /**
             * Text
             * @description Texto oficial de la carta.
             */
            text: string;
            /**
             * Attribute
             * @description Atributo de la carta.
             */
            attribute: string;
            /**
             * Prices
             * @description Precios externos de referencia; no representan el precio definitivo de una Orden.
             */
            prices: {
                [key: string]: unknown;
            };
            /**
             * Images
             * @description Metadatos externos de imágenes, todavía sin normalizar.
             */
            images: {
                [key: string]: unknown;
            };
            /**
             * Id
             * @description Identificador interno de la carta.
             */
            id: number;
            /**
             * Dateadded
             * Format: date-time
             * @description Fecha de creación con zona horaria.
             */
            dateAdded: string;
            /**
             * Dateupdated
             * @description Última actualización con zona horaria, si ocurrió.
             */
            dateUpdated?: string | null;
        };
        /** CardUpdate */
        CardUpdate: {
            /**
             * Ygoid
             * @description Identificador de la carta en la fuente externa de Yu-Gi-Oh!.
             * @example 46986414
             */
            ygoId?: number | null;
            /**
             * Sets
             * @description Sets recibidos de la fuente externa. Su estructura aún no está normalizada en campos propios.
             */
            sets?: {
                [key: string]: unknown;
            } | null;
            /**
             * Cardtype
             * @description Tipo de carta informado por la fuente externa.
             */
            cardType?: string | null;
            /**
             * Race
             * @description Raza o categoría informada por la fuente externa.
             */
            race?: string | null;
            /**
             * Name
             * @description Nombre oficial de la carta.
             */
            name?: string | null;
            /**
             * Text
             * @description Texto o efecto oficial de la carta.
             */
            text?: string | null;
            /**
             * Attribute
             * @description Atributo de la carta, cuando la fuente lo proporciona.
             */
            attribute?: string | null;
            /**
             * Prices
             * @description Precios de referencia recibidos de la fuente externa; no representan el precio definitivo de una Orden.
             */
            prices?: {
                [key: string]: unknown;
            } | null;
            /**
             * Images
             * @description Metadatos de imágenes de la fuente externa, todavía sin normalizar.
             */
            images?: {
                [key: string]: unknown;
            } | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Detail
             * @description Mensaje comprensible que explica el error recuperable.
             * @example El recurso no existe
             */
            detail: string;
        };
        /** ScrapeAcceptedResponse */
        ScrapeAcceptedResponse: {
            /**
             * Jobid
             * Format: uuid
             */
            jobId: string;
            /** Ygoid */
            ygoId: number;
            status: components["schemas"]["ScrapeJobStatus"];
            /** Statusurl */
            statusUrl: string;
            /**
             * Retryafterseconds
             * @default 2
             */
            retryAfterSeconds: number;
        };
        /** ScrapeJobResponse */
        ScrapeJobResponse: {
            /**
             * Jobid
             * Format: uuid
             */
            jobId: string;
            /** Ygoid */
            ygoId: number;
            status: components["schemas"]["ScrapeJobStatus"];
            /** Attempts */
            attempts: number;
            /**
             * Availableat
             * Format: date-time
             */
            availableAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            /** Errorcode */
            errorCode?: string | null;
        };
        /**
         * ScrapeJobStatus
         * @enum {string}
         */
        ScrapeJobStatus: "pending" | "running" | "retry_wait" | "succeeded" | "failed";
        /** ValidationErrorDetail */
        ValidationErrorDetail: {
            /** Type */
            type: string;
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Input */
            input?: unknown | null;
            /** Ctx */
            ctx?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationErrorResponse */
        ValidationErrorResponse: {
            /** Detail */
            detail: components["schemas"]["ValidationErrorDetail"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCards: {
        parameters: {
            query?: {
                /** @description Página solicitada; comienza en 1. */
                page?: number;
                /** @description Cantidad máxima de cartas por página. */
                shows?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    createCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador positivo de la carta. */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La carta no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador positivo de la carta. */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La carta no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador positivo de la carta. */
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La carta no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    searchCardListings: {
        parameters: {
            query: {
                /** @description Texto no vacío usado para buscar cartas. */
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListingResponse"][] | components["schemas"]["ScrapeAcceptedResponse"];
                };
            };
            /** @description Trabajo durable creado o reutilizado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeAcceptedResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    getCardListingScrapeJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID del trabajo durable. */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El trabajo no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    listCardListings: {
        parameters: {
            query?: {
                page?: number;
                shows?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListingListResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    getCardListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListingResponse"];
                };
            };
            /** @description No existe una identidad autenticada válida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La identidad no posee el permiso requerido. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La publicación de carta no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La entrada no cumple el contrato de la operación. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    welcome__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
