import type { components as BackendComponents } from './backend.generated';
import type { components as SearchComponents } from './search.generated';

type BackendSchema = BackendComponents['schemas'];
type SearchSchema = SearchComponents['schemas'];

export type UserCreate = BackendSchema['UserCreate'];
export type User = BackendSchema['UserResponse'];
export type UserUpdate = BackendSchema['UserUpdate'];
export type UserList = BackendSchema['UserListResponse'];
export type UserRoleAssignment = BackendSchema['UserRoleAssignment'];
export type UserAddress = BackendSchema['UserAddressResponse'];
export type UserAddressCreate = BackendSchema['UserAddressCreate'];
export type UserAddressUpdate = BackendSchema['UserAddressUpdate'];
export type UserAddressList = BackendSchema['UserAddressListResponse'];
export type Role = BackendSchema['RoleResponse'];
export type RoleCreate = BackendSchema['RoleCreate'];
export type RoleUpdate = BackendSchema['RoleUpdate'];
export type RolePermissionsUpdate = BackendSchema['RolePermissionsUpdate'];
export type Permission = BackendSchema['PermissionResponse'];
export type PermissionCode = BackendSchema['PermissionCode'];

export type CardListing = SearchSchema['CardListingResponse'];
export type CardListingList = SearchSchema['CardListingListResponse'];
export type ScrapeAccepted = SearchSchema['ScrapeAcceptedResponse'];
export type ScrapeJob = SearchSchema['ScrapeJobResponse'];
export type ScrapeJobStatus = SearchSchema['ScrapeJobStatus'];
export type CardSearchResult = CardListing[] | ScrapeAccepted;
export type OrderPeriod = BackendSchema['OrderPeriodResponse'];
export type OrderPeriodCreate = BackendSchema['OrderPeriodCreate'];
export type OrderPeriodUpdate = BackendSchema['OrderPeriodUpdate'];
export type OrderPeriodHistory = BackendSchema['OrderPeriodHistoryResponse'];
export type OrderPeriodStatus = BackendSchema['OrderPeriodStatus'];
export type OrderRequest = BackendSchema['OrderRequestResponse'];
export type OrderRequestCreate = BackendSchema['OrderRequestCreate'];
export type OrderRequestUpdate = BackendSchema['OrderRequestUpdate'];
export type OrderRequestPricingUpdate = BackendSchema['OrderRequestPricingUpdate'];
export type OrderRequestItem = BackendSchema['OrderRequestItemResponse'];
export type OrderRequestItemCreate = BackendSchema['OrderRequestItemCreate'];
export type OrderRequestItemUpdate = BackendSchema['OrderRequestItemUpdate'];
export type OrderRequestItemPricingUpdate = BackendSchema['OrderRequestItemPricingUpdate'];
export type OrderRequestHistory = BackendSchema['OrderRequestHistoryResponse'];
export type OrderRequestStatus = BackendSchema['OrderRequestStatus'];
export type OrderPeriodList = BackendSchema['OrderPeriodListResponse'];
export type OrderRequestList = BackendSchema['OrderRequestListResponse'];
export type OrderTracking = BackendSchema['OrderTrackingResponse'];
export type DeliveryPreferenceUpdate = BackendSchema['DeliveryPreferenceUpdate'];
export type InternationalShipment = BackendSchema['InternationalShipmentResponse'];
export type InternationalShipmentCreate = BackendSchema['InternationalShipmentCreate'];
export type InternationalShipmentUpdate = BackendSchema['InternationalShipmentUpdate'];
export type DeliveryEventCreate = BackendSchema['DeliveryEventCreate'];
export type FulfillmentCreate = BackendSchema['FulfillmentCreate'];
export type Fulfillment = BackendSchema['FulfillmentResponse'];
export type DeliveryStage = BackendSchema['DeliveryStageResponse'];
export type DeliveryStageCreate = BackendSchema['DeliveryStageCreate'];
export type DeliveryStageUpdate = BackendSchema['DeliveryStageUpdate'];
export type DeliveryStageScope = BackendSchema['DeliveryStageScope'];
