<script lang="ts">
	import { onMount } from 'svelte';
	import { getApiErrorMessage } from '../../lib/api/client';
	import { permissionsApi, rolesApi } from '../../lib/api/users';
	import type { Permission, PermissionCode, Role } from '../../lib/api/types';
	export let id: number | null = null;
	let role: Role | null = null, permissions: Permission[] = [], selected: string[] = [], name = '', description = '', loading = true, saving = false, error = '', notice = '';
	async function load() { try { permissions = await permissionsApi.list(); if (id) { role = await rolesApi.get(id); name = role.name; description = role.description ?? ''; selected = role.permissions?.map((item) => item.code) ?? []; } } catch (caught) { error = getApiErrorMessage(caught); } finally { loading = false; } }
	async function save() { saving = true; error = ''; try { if (id) { if (!role?.isSystem) role = await rolesApi.update(id, { name, description: description || null }); role = await rolesApi.replacePermissions(id, { permissions: selected as PermissionCode[] }); notice = 'El rol se actualizó.'; } else { const created = await rolesApi.create({ name, description: description || null }); await rolesApi.replacePermissions(created.id, { permissions: selected as PermissionCode[] }); window.location.assign(`/admin/roles/${created.id}`); } } catch (caught) { error = getApiErrorMessage(caught); } finally { saving = false; } }
	async function remove() { if (!id || role?.isSystem || !window.confirm('¿Eliminar este rol?')) return; try { await rolesApi.remove(id); window.location.assign('/admin/roles'); } catch (caught) { error = getApiErrorMessage(caught); } }
	onMount(load);
</script>
{#if loading}<p class="state-box">Cargando el rol…</p>{:else}<form class="semantic-form wide-form" on:submit|preventDefault={save}><label><span class="label">Nombre</span><input class="field" required bind:value={name} disabled={role?.isSystem || saving} /></label><label><span class="label">Descripción</span><textarea class="field" rows="3" bind:value={description} disabled={role?.isSystem || saving}></textarea></label><fieldset><legend>Permisos</legend><div class="permission-grid">{#each permissions as permission}<label><input type="checkbox" value={permission.code} bind:group={selected} disabled={saving} /><span><strong>{permission.code}</strong><small>{permission.description}</small></span></label>{/each}</div></fieldset>{#if role?.isSystem}<p class="field-hint">El nombre del rol del sistema no se puede cambiar. Sus permisos sí se pueden revisar y guardar.</p>{/if}{#if error}<p class="error-text" role="alert">{error}</p>{/if}{#if notice}<p role="status">{notice}</p>{/if}<div class="action-row"><button class="button" type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar rol'}</button>{#if id && !role?.isSystem}<button class="button-danger" type="button" on:click={remove}>Eliminar rol</button>{/if}</div></form>{/if}
