<script lang="ts">
	import { onMount } from 'svelte';
	import { deliveryStagesApi, shipmentsApi } from '../../lib/api/deliveries';
	import { getApiErrorMessage } from '../../lib/api/client';
	import type { DeliveryStage, InternationalShipment } from '../../lib/api/types';
	import { formatDate } from '../../lib/workflow';
	export let id: number;
	let shipment: InternationalShipment | null = null, stages: DeliveryStage[] = [], name = '', reference = '', stageKey = '', note = '', correctionId = '', correctionReason = '', error = '', notice = '';
	async function load() { try { [shipment, stages] = await Promise.all([shipmentsApi.get(id), deliveryStagesApi.list('international')]); name = shipment.name; reference = shipment.reference ?? ''; stageKey = shipment.currentStage.key; } catch (caught) { error = getApiErrorMessage(caught); } }
	async function saveDetails() { if (!shipment) return; try { shipment = await shipmentsApi.update(id, { name, reference: reference || null }); notice = 'Los datos del envío se guardaron.'; } catch (caught) { error = getApiErrorMessage(caught); } }
	async function addEvent() { try { shipment = await shipmentsApi.addEvent(id, { stageKey, note: note || null, correctionOfEventId: correctionId ? Number(correctionId) : null, correctionReason: correctionId ? correctionReason : null }); note = ''; correctionId = ''; correctionReason = ''; notice = 'La etapa se registró.'; } catch (caught) { error = getApiErrorMessage(caught); } }
	onMount(load);
</script>
{#if !shipment && !error}<p class="state-box">Cargando envío…</p>{:else if error && !shipment}<p class="state-box error-text">{error}</p>{:else if shipment}<section class="detail-section"><div class="section-heading"><div><p class="route-label">ENVÍO #{shipment.id}</p><h1>{shipment.name}</h1></div><span class="status">{shipment.currentStage.name}</span></div><form class="semantic-form compact-form" on:submit|preventDefault={saveDetails}><label><span class="label">Nombre</span><input class="field" bind:value={name} required /></label><label><span class="label">Referencia</span><input class="field" bind:value={reference} /></label><button class="button-secondary">Guardar datos</button></form></section><section class="detail-section"><h2>Registrar etapa</h2><form class="semantic-form compact-form" on:submit|preventDefault={addEvent}><label><span class="label">Etapa</span><select class="field" bind:value={stageKey}>{#each stages as stage}<option value={stage.key}>{stage.name}</option>{/each}</select></label><label><span class="label">Nota</span><textarea class="field" bind:value={note}></textarea></label><label><span class="label">Corrige el evento # <span class="optional">(opcional)</span></span><input class="field" type="number" min="1" bind:value={correctionId} /></label>{#if correctionId}<label><span class="label">Motivo de la corrección</span><textarea class="field" required bind:value={correctionReason}></textarea></label>{/if}<button class="button">Registrar etapa</button></form></section>{#if error}<p class="error-text" role="alert">{error}</p>{/if}{#if notice}<p role="status">{notice}</p>{/if}<section class="detail-section"><h2>Asignaciones</h2><div class="responsive-list">{#each shipment.allocations as allocation}<article><div><strong>Orden #{allocation.orderRequestId}</strong><p>Ítem #{allocation.orderRequestItemId} · {allocation.quantity} unidades</p></div></article>{/each}</div></section><section class="detail-section"><h2>Eventos</h2><ol class="timeline">{#each shipment.events as event}<li><strong>{event.stageName ?? event.stageKey ?? 'Evento'}</strong><span>{formatDate(event.occurredAt)}{event.note ? ` · ${event.note}` : ''}{event.correctionOfEventId ? ` · Corrige #${event.correctionOfEventId}` : ''}</span></li>{/each}</ol></section>{/if}
